# Generated by Django 5.0.6 on 2024-07-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20)),
                ('pw', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('std_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('birth', models.DateField()),
                ('tel', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('in_date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=255)),
                ('insert_date', models.DateField(auto_now_add=True)),
                ('insert_user', models.CharField(max_length=50)),
                ('deleted', models.CharField(max_length=1)),
            ],
        ),
    ]
