# Generated by Django 5.0.6 on 2024-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='It_plan',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('schedule', models.CharField(max_length=100)),
                ('insert_date', models.DateField(auto_now_add=True)),
                ('insert_user', models.CharField(max_length=50)),
                ('deleted', models.CharField(max_length=1)),
            ],
        ),
    ]
