# Generated by Django 5.0.6 on 2024-08-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('reply_no', models.IntegerField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('insert_user', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('deleted', models.CharField(max_length=1)),
            ],
        ),
    ]
