# Generated by Django 5.0.6 on 2024-07-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('doc_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=50)),
                ('write_date', models.DateField()),
                ('viewer', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=255)),
                ('insert_date', models.DateField(auto_now_add=True)),
                ('insert_user', models.CharField(max_length=50)),
                ('deleted', models.CharField(max_length=1)),
                ('insert_std', models.CharField(max_length=50)),
            ],
        ),
    ]
